name: Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  qc:
    name: Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.2

      - name: Compile datasets file
        run: bun install && bun run compile

      - name: Check datasets file
        run: bun qc